# 서버 배포시 사용해야할 docker-compose yml
version: '3'

networks:
  net:
    driver: bridge

services:
  nginx:
    container_name: nginx
    networks:
      - net
    depends_on:
      - nest
    image: nginx:1.25.4-alpine-slim
    environment:
      - "TZ=Asia/Seoul"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
  nest:
    container_name: nest
    networks:
      - net
    image: daeseong0226/office-nest
    ports:
      - "3000:3000"
    volumes:
      - .env:/app/.env
      - .npmrc:/app/.npmrc
    command: sh -c "rm -rf node_modules && npm install && npm run build && npm run start:prod"
