# 개발 환경용 도커
version: '3'

networks:
  net:
    driver: bridge

services:
  postgres:
    image: postgres:15.6-alpine3.19
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: daeseong0226
      POSTGRES_PASSWORD: 
      POSTGRES_DB: office
  nest:
    container_name: nest
    networks:
      - net
    image: daeseong0226/office-nest
    ports:
      - "3000:3000"
    volumes:
      - .env:/app/.env
      - .npmrc:/app/.npmrc
      - ./:/workspace
    command: sh -c "npm install && npm run build && npm run start:prod"
